In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# Demo dataset for the graphs : 
dataset  = sns.get_dataset_names()
dataset

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [5]:
df = sns.load_dataset('diamonds')

In [6]:
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [ ]:
# Load Plotly : 
import plotly.express as px

In [9]:
# Bar plot using plotly : 
px.bar(data_frame=df , x=df['cut'])

In [13]:
px.bar(df , x='cut' , color = 'color') # We can make the bar plot using the color method as well.

In [14]:
px.bar(df , x = 'cut' , color='cut' , color_discrete_sequence=['red' , ' blue' , 'green' , 'black' ])

In [ ]:
data  = df.groupby(['cut']).size().rename('cut_count').reset_index()

C:\Users\vinay\AppData\Local\Temp\ipykernel_7748\603210582.py:1: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [18]:
data.head()

         cut  cut_count
0      Ideal      21551
1    Premium      13791
2  Very Good      12082
3       Good       4906
4       Fair       1610

In [20]:
px.bar(data  , x='cut' , y='cut_count' , text='cut_count')