In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Demo dataset for the graphs : 
dataset  = sns.get_dataset_names()
dataset

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [3]:
df = sns.load_dataset('diamonds')

In [4]:
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [5]:
# Load Plotly : 
import plotly.express as px

In [12]:
# Bar plot using plotly : 
px.bar(data_frame=df , x='cut')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'cut=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['Ideal', 'Premium', 'Good', ..., 'Very Good', 'Premium', 'Ideal'],
                         shape=(53940,), dtype=object),
              'xaxis': 'x',
              'y': {'bdata': ('AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ' ... 'EBAQEBAQEBAQEBAQEBAQEBAQEBAQEB'),
                    'dtype': 'i1'},
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'cut'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})

In [7]:
px.bar(df , x='cut' , color = 'color') # We can make the bar plot using the color method as well.

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'color=E<br>cut=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': 'E',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': 'E',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['Ideal', 'Premium', 'Good', ..., 'Premium', 'Very Good', 'Very Good'],
                         shape=(9797,), dtype=object),
              'xaxis': 'x',
              'y': {'bdata': ('AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ' ... 'EBAQEBAQEBAQEBAQEBAQEBAQEBAQE='),
                    'dtype': 'i1'},
              'yaxis': 'y'},
             {'hovertemplate': 'color=I<br>cut=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': 'I',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': 'I',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['Premium', 'Very Good', 'Ideal', ..., 'Ideal', 'Ideal', 'Ideal'],
                         shape=(5422,), dtype=object),
              'xaxis': 'x',
              'y': {'bdata': ('AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ' ... 'EBAQEBAQEBAQEBAQEBAQEBAQEBAQ=='),
                    'dtype': 'i1'},
              'yaxis': 'y'},
             {'hovertemplate': 'color=J<br>cut=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': 'J',
              'marker': {'color': '#00cc96', 'pattern': {'shape': ''}},
              'name': 'J',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['Good', 'Very Good', 'Good', ..., 'Ideal', 'Ideal', 'Very Good'],
                         shape=(2808,), dtype=object),
              'xaxis': 'x',
              'y': {'bdata': ('AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ' ... 'EBAQEBAQEBAQEBAQEBAQEBAQEBAQEB'),
                    'dtype': 'i1'},
              'yaxis': 'y'},
             {'hovertemplate': 'color=H<br>cut=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': 'H',
              'marker': {'color': '#ab63fa', 'pattern': {'shape': ''}},
              'name': 'H',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['Very Good', 'Very Good', 'Very Good', ..., 'Ideal', 'Ideal', 'Premium'],
                         shape=(8304,), dtype=object),
              'xaxis': 'x',
              'y': {'bdata': ('AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ' ... 'EBAQEBAQEBAQEBAQEBAQEBAQEBAQEB'),
                    'dtype': 'i1'},
              'yaxis': 'y'},
             {'hovertemplate': 'color=F<br>cut=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': 'F',
              'marker': {'color': '#FFA15A', 'pattern': {'shape': ''}},
              'name': 'F',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['Premium', 'Very Good', 'Very Good', ..., 'Premium', 'Good', 'Premium'],
                         shape=(9542,), dtype=object),
              'xaxis': 'x',
              'y': {'bdata': ('AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ' ... 'EBAQEBAQEBAQEBAQEBAQEBAQEBAQE='),
                    'dtype': 'i1'},
              'yaxis': 'y'},
             {'hovertemplate': 'color=G<br>cut=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': 'G',
              'marker': {'color': '#19d3f3', 'pattern': {'shape': ''}},
              'name': 'G',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['Very Good', 'Ideal', 'Ideal', ..., 'Ideal', 'Good', 'Ideal'],
                         shape=(11292,), dtype=object),
              'xaxis': 'x',
              'y': {'bdata': ('AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ' ... 'EBAQEBAQEBAQEBAQEBAQEBAQEBAQEB'),
                    'dtype': 'i1'},
              'yaxis': 'y'},
             {'hovertemplate': 'color=D<br>cut=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': 'D',
              'marker': {'color': '#FF6692', 'pattern': {'shape': ''}},
              'name': 'D',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['Very Good', 'Very Good', 'Very Good', ..., 'Good', 'Very Good',
                          'Ideal'], shape=(6775,), dtype=object),
              'xaxis': 'x',
              'y': {'bdata': ('AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ' ... 'EBAQEBAQEBAQEBAQEBAQEBAQEBAQ=='),
                    'dtype': 'i1'},
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'color'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'cut'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})

In [8]:
px.bar(df , x = 'cut' , color='cut' , color_discrete_sequence=['red' , ' blue' , 'green' , 'black' ])

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'cut=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': 'Ideal',
              'marker': {'color': 'red', 'pattern': {'shape': ''}},
              'name': 'Ideal',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['Ideal', 'Ideal', 'Ideal', ..., 'Ideal', 'Ideal', 'Ideal'],
                         shape=(21551,), dtype=object),
              'xaxis': 'x',
              'y': {'bdata': ('AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ' ... 'EBAQEBAQEBAQEBAQEBAQEBAQEBAQE='),
                    'dtype': 'i1'},
              'yaxis': 'y'},
             {'hovertemplate': 'cut=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': 'Premium',
              'marker': {'color': ' blue', 'pattern': {'shape': ''}},
              'name': 'Premium',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['Premium', 'Premium', 'Premium', ..., 'Premium', 'Premium', 'Premium'],
                         shape=(13791,), dtype=object),
              'xaxis': 'x',
              'y': {'bdata': ('AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ' ... 'EBAQEBAQEBAQEBAQEBAQEBAQEBAQEB'),
                    'dtype': 'i1'},
              'yaxis': 'y'},
             {'hovertemplate': 'cut=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': 'Good',
              'marker': {'color': 'green', 'pattern': {'shape': ''}},
              'name': 'Good',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['Good', 'Good', 'Good', ..., 'Good', 'Good', 'Good'],
                         shape=(4906,), dtype=object),
              'xaxis': 'x',
              'y': {'bdata': ('AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ' ... 'EBAQEBAQEBAQEBAQEBAQEBAQEBAQ=='),
                    'dtype': 'i1'},
              'yaxis': 'y'},
             {'hovertemplate': 'cut=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': 'Very Good',
              'marker': {'color': 'black', 'pattern': {'shape': ''}},
              'name': 'Very Good',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['Very Good', 'Very Good', 'Very Good', ..., 'Very Good', 'Very Good',
                          'Very Good'], shape=(12082,), dtype=object),
              'xaxis': 'x',
              'y': {'bdata': ('AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ' ... 'EBAQEBAQEBAQEBAQEBAQEBAQEBAQ=='),
                    'dtype': 'i1'},
              'yaxis': 'y'},
             {'hovertemplate': 'cut=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': 'Fair',
              'marker': {'color': 'red', 'pattern': {'shape': ''}},
              'name': 'Fair',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['Fair', 'Fair', 'Fair', ..., 'Fair', 'Fair', 'Fair'],
                         shape=(1610,), dtype=object),
              'xaxis': 'x',
              'y': {'bdata': ('AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ' ... 'EBAQEBAQEBAQEBAQEBAQEBAQEBAQE='),
                    'dtype': 'i1'},
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'cut'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y',
                         'categoryarray': [Ideal, Premium, Good, Very Good, Fair],
                         'categoryorder': 'array',
                         'domain': [0.0, 1.0],
                         'title': {'text': 'cut'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})

In [9]:
data  = df.groupby(['cut']).size().rename('cut_count').reset_index()

C:\Users\vinay\AppData\Local\Temp\ipykernel_3528\603210582.py:1: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [10]:
data.head()

         cut  cut_count
0      Ideal      21551
1    Premium      13791
2  Very Good      12082
3       Good       4906
4       Fair       1610

In [11]:
px.bar(data  , x='cut' , y='cut_count' , text='cut_count')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'cut=%{x}<br>cut_count=%{text}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'text': {'bdata': 'AAAAAMAL1UAAAAAAgO/KQAAAAAAAmcdAAAAAAAAqs0AAAAAAACiZQA==', 'dtype': 'f8'},
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['Ideal', 'Premium', 'Very Good', 'Good', 'Fair'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'L1TfNTIvKhNKBg==', 'dtype': 'i2'},
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'cut'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'cut_count'}}}
})